load("@aspect_bazel_lib//lib:run_binary.bzl", "run_binary")
load("@aspect_bazel_lib//lib:copy_to_directory.bzl", "copy_to_directory")
load("@rules_java//java:defs.bzl", "java_binary", "java_library")

java_library(
    name = "AiShared",
    srcs = glob(["src/com/google/appinventor/shared/**/*.java"]),
    deps = [
        "//appinventor/common:CommonUtils",
        "//appinventor/common:CommonVersion", 
        "//appinventor/common:CommonConstants",
        "//appinventor/components:CommonConstants",
        "//appinventor/lib:WarLibs",
        "//appinventor/lib:ProtobufAppEngine",
    ],
)

java_library(
    name = "AiServer",
    srcs = glob([
        "src/com/google/appinventor/server/**/*.java",
        "src/com/google/appinventor/server/**/*.properties",
    ]),
    deps = [
        ":AiShared",
        "//appinventor/common:CommonUtils",
        "//appinventor/common:CommonVersion",
        "//appinventor/common:CommonConstants", 
        "//appinventor/components:CommonConstants",
        "//appinventor/lib:LocalJarsForGwtSdk",
        "//appinventor/lib:WarLibs",
        "//appinventor/lib:ProtobufAppEngine",
    ],
)

java_library(
    name = "AiRebind",
    srcs = glob(["src/com/google/appinventor/rebind/**/*.java"]),
    deps = [
        "//appinventor/lib:LocalJarsForGwtSdk",
    ],
)

java_library(
    name = "AiClientLib",
    srcs = glob([
        "src/com/google/appinventor/client/**/*.java",
        "src/com/google/appinventor/shared/**/*.java",
    ]) + [
        ":GeneratedFilesFromComponents",
    ],
    resources = glob([
        "src/com/google/appinventor/client/**/*.ui.xml",
        "src/com/google/appinventor/images/*.png",
        "src/com/google/appinventor/images/*.gif",
        "src/com/google/appinventor/client/languages.json",
        "src/com/google/appinventor/client/utils/html5dnd.js",
        "src/com/google/appinventor/YaClient.gwt.xml",
        "src/**/*.gwt.xml",
    ]) + [
        ":GenerateBlocklyTranslation",
        ":GeneratedFilesFromComponents",  # This includes simple_components.json
    ],
    deps = [
        "//appinventor/common:CommonUtils",
        "//appinventor/common:CommonVersion", 
        "//appinventor/components:CommonConstants",
        "//appinventor/lib:LocalJarsForGwtSdk",
        "//appinventor/lib:LocalJarsForYaClientApp",
    ],
)

genrule(
    name = "YaClientApp",
    srcs = [
        ":AiClientLib",
        ":AiRebind",
        "//appinventor/blocklyeditor:BlocklyCompile",
        "//appinventor/common:CommonUtils",
        "//appinventor/common:CommonVersion", 
        "//appinventor/components:CommonConstants",
    ],
    outs = [
        "ode/ode.nocache.js",
        "ode/compilation-mappings.txt",
    ],
    cmd_bash = """
        $(location //appinventor/lib:GwtCompiler) \\
            -Xss2M -Xmx4G \\
            -war $(RULEDIR) \\
            -logLevel INFO \\
            -style pretty \\
            com.google.appinventor.YaClient-dev
    """,
    cmd_bat = """
        $(location //appinventor/lib:GwtCompiler) ^
            -Xss2M -Xmx4G ^
            -war $(RULEDIR) ^
            -logLevel INFO ^
            -style pretty ^
            com.google.appinventor.YaClient-dev
    """,
    tools = [
        "//appinventor/lib:GwtCompiler",
    ],
)

GENERATED_FILES_SRC = "$(GENDIR)/appinventor/components/_javac/AndroidRuntime/libAndroidRuntime_sources/"

genrule(
    name = "GeneratedFilesFromComponents",
    srcs = ["//appinventor/components:AndroidRuntime"],
    outs = [
        "src/com/google/appinventor/client/ComponentEventTranslations.java",
        "src/com/google/appinventor/client/ComponentInfoTranslations.java",
        "src/com/google/appinventor/client/ComponentMethodTranslations.java",
        "src/com/google/appinventor/client/ComponentPropertyTranslations.java",
        "src/com/google/appinventor/client/ComponentTranslationTable.java",
        "src/com/google/appinventor/simple_components.json",
    ],
    cmd_bash = 'mkdir -p "$(RULEDIR)/src/" && cp "{}" "$(RULEDIR)/src/"'.format(
        GENERATED_FILES_SRC,
    ),
    cmd_bat = 'xcopy /Y /I /F /E "{}" "$(RULEDIR)\\src\\"'.format(
        GENERATED_FILES_SRC.replace("/", "\\"),
    ),
)

AI_BLOCKLY_MSG_DIR = "$(GENDIR)/../../../appinventor/blocklyeditor/src/msg/ai_blockly"

BLOCKLY_MSG_JSON_DIR = "$(GENDIR)/../../../appinventor/lib/blockly/msg/json"

BLOCKLY_TRANSLATION_DEST = "$(RULEDIR)"

run_binary(
    name = "GenerateBlocklyTranslation",
    outs = [
        "messages.nocache.js",
        "messages_ca.nocache.js",
        "messages_de.nocache.js",
        "messages_es.nocache.js",
        "messages_fr.nocache.js",
        "messages_he.nocache.js",
        "messages_hu.nocache.js",
        "messages_hy.nocache.js",
        "messages_it.nocache.js",
        "messages_ko.nocache.js",
        "messages_lt.nocache.js",
        "messages_nl.nocache.js",
        "messages_pl.nocache.js",
        "messages_pt.nocache.js",
        "messages_pt_BR.nocache.js",
        "messages_ru.nocache.js",
        "messages_sv.nocache.js",
        "messages_tr.nocache.js",
        "messages_zh_CN.nocache.js",
        "messages_zh_TW.nocache.js",
        "i18n.java",
    ],
    args = [
        AI_BLOCKLY_MSG_DIR,
        BLOCKLY_MSG_JSON_DIR,
        BLOCKLY_TRANSLATION_DEST,
        "false",  # release flag - matches ${release} from build.xml
    ],
    tool = "//appinventor/blocklyeditor:BlocklyTranslationGenerator",
)


run_binary(
    name = "BuildYaClientApp",
    args = [
        "-XdisableUpdateCheck",
        "-localWorkers",
        "4",
        #        "-optimize",
        #        "9",
        "-draftCompile",
        "-war",
        "$(GENDIR)/appinventor/appengine/war",
        #        "-extra",
        #        "$(GENDIR)/appinventor/appengine/extra",
        "-logLevel",
        "INFO",
        "com.google.appinventor.YaClient",
    ],
    out_dirs = [
        #        "extra",
        "war",
    ],
    tool = ":YaClientApp",
)

filegroup(
    name = "War",
    srcs = glob(["war/**"]),
)

genrule(
    name = "AuthKey",
    outs = [
        "authkey/meta",
        "authkey/1",
    ],
    cmd_bash = "&&".join([
        "{keyczar} create --purpose=crypt --location={output_dir}",
        "{keyczar} addkey --location={output_dir}",
        "{keyczar} promote --version=1 --location={output_dir}",
    ]).format(
        keyczar = "$(location //appinventor/lib:KeyczarTool)",
        output_dir = "$(RULEDIR)/authkey",
    ),
    cmd_bat = "&&".join([
        "{keyczar} create --purpose=crypt --location=\"{output_dir}\"",
        "{keyczar} addkey --location=\"{output_dir}\"",
        "{keyczar} promote --version=1 --location=\"{output_dir}\"",
    ]).format(
        keyczar = "$(location //appinventor/lib:KeyczarTool)",
        output_dir = "$(RULEDIR)/authkey",
    ),
    tools = [
        "//appinventor/lib:KeyczarTool",
    ],
)

genrule(
    name = "Keystore",
    outs = [
        "keystore/meta",
        "keystore/1",
    ],
    cmd_bash = "&&".join([
        "{keyczar} create --purpose=crypt --location=\"{output_dir}\"",
        "{keyczar} addkey --location=\"{output_dir}\"",
        "{keyczar} promote --version=1 --location=\"{output_dir}\"",
    ]).format(
        keyczar = "$(location //appinventor/lib:KeyczarTool)",
        output_dir = "$(RULEDIR)/keystore",
    ),
    cmd_bat = "&&".join([
        "{keyczar} create --purpose=crypt --location=\"{output_dir}\"",
        "{keyczar} addkey --location=\"{output_dir}\"",
        "{keyczar} promote --version=1 --location=\"{output_dir}\"",
    ]).format(
        keyczar = "$(location //appinventor/lib:KeyczarTool)",
        output_dir = "$(RULEDIR)/keystore",
    ),
    tools = [
        "//appinventor/lib:KeyczarTool",
    ],
)


copy_to_directory(
    name = "MakeWar",
    srcs = [
        ":AiServer",
        ":AiShared",
        ":AuthKey",
        ":BuildYaClientApp",
        ":Keystore",
        ":War",
        "//appinventor/blocklyeditor:media",
        "//appinventor/lib:WarLibs",
    ],
    replace_prefixes = {
        "appinventor/lib/**/": "war/WEB-INF/lib/",
        "libAiShared.jar": "war/WEB-INF/lib/libAiShared.jar",
        "libAiServer.jar": "war/WEB-INF/lib/libAiServer.jar",
        "appinventor/appengine/war/*": "war/",
        #        "appinventor/appengine/extra/*": "extra/",
        "authkey": "war/WEB-INF/authkey/",
        "keystore": "war/keystore/",
        #        "appinventor/blocklyeditor/media/*.css": "war/static/css/",
        #        "appinventor/blocklyeditor/media/*.[!css]": "war/static/media/",
    },
)
