plugins {
//    java
    war
    id("org.docstr.gwt")
}

group = "com.google.appinventor"
version = "unspecified"

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(8))
    }
    sourceSets {
        main {
            java {
                // FIXME: This requires us to run :components:assembleRelease first.
                // Adds the annotation processor output to the classpath
                // - AutogeneratedOdeMessages.java
                // - ComponentTranslation.java
                srcDirs("../components/build/generated/ap_generated_sources/release/out/")
                exclude("*.md", "*.json", "*.txt")
            }
        }
    }
}

tasks.withType<JavaCompile> {
    options.encoding = "UTF-8"
}

//project(":components").afterEvaluate {
//    java.sourceSets["main"].java.srcDir(
//        project(":components").sourceSets["main"].output.generatedSourcesDirs.files.filter {
//            it.name in listOf(
//                "AutogeneratedOdeMessages.java",
//                "ComponentsTranslation.java"
//            )
//        }
//    )
//}

gwt {
    gwtVersion = "2.10.0"
    modules("com.google.appinventor.YaClient")
    devModules("com.google.appinventor.YaClient-dev")

    maxHeapSize = "1G"
    compiler.strict = true
    println("##### SRC: ${src.files}")
//    println("##### CLASSPATH: ${}")
    println("##### MODULES: ${modules}")
//    logLevel = org.docstr.gradle.plugins.gwt.LogLevel.ALL

//    src += files(tasks.compileJava.get().options.generatedSourceOutputDirectory)
//    src += files(project(":common-utils").sourceSets["main"].allJava) + files(project(":common-utils").sourceSets["main"].resources)
}

dependencies {
    gwt(projects.commonUtils)
    gwt(projects.commonVersion)
    gwt(projects.componentConstants)
    gwt(projects.appengineShared)
    implementation(projects.commonUtils)
    implementation(projects.commonVersion)
    implementation(projects.componentConstants)
    implementation(projects.appengineShared)
    implementation("com.google.gwt:gwt-user:2.10.0")
    implementation("com.google.gwt:gwt-dev:2.10.0")
    implementation("com.allen-sauer.gwt.dnd:gwt-dnd:3.2.3")
    implementation("com.googlecode.gwtquery:gwtquery:1.5-beta1")
    implementation("com.google.gwt:gwt-incubator:2.0.1")
    implementation("org.pepstock:charba:2.5")
    implementation("org.json:json:20220320")
}
